### ISSUE TITLE
bootstrap 4 beta.

### ISSUE THREAD

**Issue by ghost** [dmxt/bootstrap4-scss-gulp-starter-kit#3]
You should update this to bootstrap 4 beta since it has been released now to the public.

**Comment by Sylk** [comment]
Close this.

**Comment by dmxt** [comment]
Ah, the old time when I didn't know how to properly respond to issues.

I did fix the issue, forgot to close it and thanks to the reminder comment, it got closed. I should have commented in first place. My bad. 😀
